### ISSUE TITLE
No longer building due to  undefined: jwt.StandardClaims error

### ISSUE THREAD

**Issue by ghost** [thewhitetulip/Tasks#28]
when trying to build the app the following error is returned. 

` github.com/thewhitetulip/Tasks/views
views/api.go:19: undefined: jwt.StandardClaims`

I've taken a look here -> https://godoc.org/github.com/dgrijalva/jwt-go#example-NewWithClaims--CustomClaimsType

and the code in api.go seems to be exactly the same.
Not sure what the issue is.

I'm trying to build using -> go version go1.8.3 darwin/amd64

Regards,
J.

**Comment by ghost** [comment]
Er, ignore this - tried again after re-running go get and all works - apologies.
